[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
remappings = [
  "forge-std/=lib/forge-std/src/",
  "poseidon-solidity/=lib/poseidon-solidity/contracts/",
  "zk-kit.solidity/=lib/zk-kit.solidity/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "davinci-contracts/=lib/davinci-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
