/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as resultsverifierVkeySol from "./resultsverifier_vkey.sol";
export type { resultsverifierVkeySol };
import type * as statetransitionVkeySol from "./statetransition_vkey.sol";
export type { statetransitionVkeySol };
export type { ResultsVerifierGroth16 } from "./ResultsVerifierGroth16";
export type { StateTransitionVerifierGroth16 } from "./StateTransitionVerifierGroth16";
