/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
import type * as verifiers from "./verifiers";
export type { verifiers };
export type { ProcessRegistry } from "./ProcessRegistry";
