#!/bin/bash

JSON_FILE="$(mktemp)"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
$SCRIPT_DIR/parse_deployall_runs.sh > $JSON_FILE

# Script to generate Go constants
# This script reads the JSON file and creates hardcoded address constants

set -euo pipefail

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed. Please install jq to run this script."
    exit 1
fi

# Define output files
OUTPUT_FILE="golang-types/addresses.go"

# Check if JSON file exists
if [ ! -f "$JSON_FILE" ]; then
    echo "Error: $JSON_FILE not found"
    exit 1
fi

echo "Generating Go constants from $JSON_FILE to $OUTPUT_FILE..."

# Create the golang-types directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Start generating the Go file
cat > "$OUTPUT_FILE" << EOF
package contracts

// This file is auto-generated by helpers/write_contract_addresses.sh
// Do not edit manually - run the script to regenerate

// Network constants
const (
	SepoliaNetwork = "sepolia"
	UzhNetwork     = "uzh"
	MainnetNetwork = "mainnet"
	BaseNetwork    = "base"
	CeloNetwork    = "celo"
	TestNetwork    = "test"
)

// AvailableNetworksByName contains the list of networks where Davinci is deployed.
var AvailableNetworksByName = map[string]uint32{
	SepoliaNetwork: 11155111,
	UzhNetwork:     710,
	CeloNetwork:    42220,
	MainnetNetwork: 1,
	BaseNetwork:    8453,
	TestNetwork:    1337, // Local test network
}

// AvailableNetworksByID contains the list of networks where Davinci is deployed.
var AvailableNetworksByID = map[uint32]string{
	11155111: SepoliaNetwork,
	710:      UzhNetwork,
	42220:    CeloNetwork,
	1:        MainnetNetwork,
	8453:     BaseNetwork,
	1337:     TestNetwork,
}

// Contract name constants
const (
	ProcessRegistryContract                = "processRegistry"
	StateTransitionVerifierGroth16Contract = "stateTransitionVerifierGroth16"
	ResultsVerifierGroth16Contract         = "resultsVerifierGroth16"
	SequencerRegistryContract              = "sequencerRegistry"
)

// Dummy consts until we deploy on Mainnet and develop SequencerRegistry
const (
	ProcessRegistryMainnetAddress = "0x0"
	ResultsVerifierGroth16MainnetAddress = "0x0"
	SequencerRegistryBaseAddress = "0x0"
	SequencerRegistryCeloAddress = "0x0"
	SequencerRegistryMainnetAddress = "0x0"
	SequencerRegistrySepoliaAddress = "0x0"
	SequencerRegistryUzhAddress = "0x0"
	StateTransitionVerifierGroth16MainnetAddress = "0x0"
)

// Contract addresses by network
const (
EOF

# Generate address constants for each contract and network combination
for contract in $(jq -r 'keys[]' "$JSON_FILE"); do
    # Convert contract name to Go constant format (camelCase to PascalCase)
    contract_const=$(echo "$contract" | sed -r 's/(^|_)([a-z])/\U\2/g')

    for network in $(jq -r ".$contract | keys[]" "$JSON_FILE"); do
        # Convert network name to Go constant format
        network_const=$(echo "$network" | sed 's/^./\U&/')

        # Get the address
        address=$(jq -r ".$contract.$network" "$JSON_FILE")

        # Generate the constant
        echo "	${contract_const}${network_const}Address = \"$address\"" >> "$OUTPUT_FILE"
    done
done

# Close the constants block
echo ")" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Generate helper functions
cat >> "$OUTPUT_FILE" << 'EOF'
// GetContractAddress returns the address for a given contract and network
func GetContractAddress(contract, network string) string {
	switch contract {
	case ProcessRegistryContract:
		switch network {
		case SepoliaNetwork:
			return ProcessRegistrySepoliaAddress
		case UzhNetwork:
			return ProcessRegistryUzhAddress
		case MainnetNetwork:
			return ProcessRegistryMainnetAddress
		case BaseNetwork:
			return ProcessRegistryBaseAddress
		case CeloNetwork:
			return ProcessRegistryCeloAddress
		}
	case StateTransitionVerifierGroth16Contract:
		switch network {
		case SepoliaNetwork:
			return StateTransitionVerifierGroth16SepoliaAddress
		case UzhNetwork:
			return StateTransitionVerifierGroth16UzhAddress
		case MainnetNetwork:
			return StateTransitionVerifierGroth16MainnetAddress
		case BaseNetwork:
			return StateTransitionVerifierGroth16BaseAddress
		case CeloNetwork:
			return StateTransitionVerifierGroth16CeloAddress
		}
	case ResultsVerifierGroth16Contract:
		switch network {
		case SepoliaNetwork:
			return ResultsVerifierGroth16SepoliaAddress
		case UzhNetwork:
			return ResultsVerifierGroth16UzhAddress
		case MainnetNetwork:
			return ResultsVerifierGroth16MainnetAddress
		case BaseNetwork:
			return ResultsVerifierGroth16BaseAddress
		case CeloNetwork:
			return ResultsVerifierGroth16CeloAddress
		}
	case SequencerRegistryContract:
		switch network {
		case SepoliaNetwork:
			return SequencerRegistrySepoliaAddress
		case UzhNetwork:
			return SequencerRegistryUzhAddress
		case MainnetNetwork:
			return SequencerRegistryMainnetAddress
		case BaseNetwork:
			return SequencerRegistryBaseAddress
		case CeloNetwork:
			return SequencerRegistryCeloAddress
		}
	}
	return ""
}

// GetAllContractAddresses returns a map of all contract addresses for a given network
func GetAllContractAddresses(network string) map[string]string {
	addresses := make(map[string]string)

	contracts := []string{
		ProcessRegistryContract,
		StateTransitionVerifierGroth16Contract,
		ResultsVerifierGroth16Contract,
		SequencerRegistryContract,
	}

	for _, contract := range contracts {
		if addr := GetContractAddress(contract, network); addr != "" && addr != "0x0" {
			addresses[contract] = addr
		}
	}

	return addresses
}

// GetSepoliaAddresses returns all contract addresses for Sepolia network
func GetSepoliaAddresses() map[string]string {
	return GetAllContractAddresses(SepoliaNetwork)
}

// GetUzhAddresses returns all contract addresses for UZH network
func GetUzhAddresses() map[string]string {
	return GetAllContractAddresses(UzhNetwork)
}

// GetMainnetAddresses returns all contract addresses for Mainnet network
func GetMainnetAddresses() map[string]string {
	return GetAllContractAddresses(MainnetNetwork)
}

// GetBaseAddresses returns all contract addresses for Base network
func GetBaseAddresses() map[string]string {
	return GetAllContractAddresses(BaseNetwork)
}

// GetCeloAddresses returns all contract addresses for Celo network
func GetCeloAddresses() map[string]string {
	return GetAllContractAddresses(CeloNetwork)
}
EOF

echo "Successfully generated $OUTPUT_FILE with hardcoded contract addresses"
echo "Contract addresses have been extracted from $JSON_FILE and converted to Go constants"
