/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICensusValidator } from "./ICensusValidator";
export type { IProcessRegistry } from "./IProcessRegistry";
export type { IZKVerifier } from "./IZKVerifier";
