/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICensusValidator,
  ICensusValidatorInterface,
} from "../../../src/interfaces/ICensusValidator";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint88",
        name: "previousWeight",
        type: "uint88",
      },
      {
        indexed: false,
        internalType: "uint88",
        name: "newWeight",
        type: "uint88",
      },
    ],
    name: "WeightChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "getCensusRoot",
    outputs: [
      {
        internalType: "uint256",
        name: "root",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "root",
        type: "uint256",
      },
    ],
    name: "getRootBlockNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "root",
        type: "uint256",
      },
    ],
    name: "getTotalVotingPowerAtRoot",
    outputs: [
      {
        internalType: "uint256",
        name: "totalVotingPower",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICensusValidator__factory {
  static readonly abi = _abi;
  static createInterface(): ICensusValidatorInterface {
    return new Interface(_abi) as ICensusValidatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICensusValidator {
    return new Contract(address, _abi, runner) as unknown as ICensusValidator;
  }
}
