/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BlobsLibInterface extends Interface {
  getFunction(
    nameOrSignature: "calcBlobHashV1" | "verifyBlobDataIsAvailable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calcBlobHashV1",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBlobDataIsAvailable",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calcBlobHashV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyBlobDataIsAvailable",
    data: BytesLike
  ): Result;
}

export interface BlobsLib extends BaseContract {
  connect(runner?: ContractRunner | null): BlobsLib;
  waitForDeployment(): Promise<this>;

  interface: BlobsLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calcBlobHashV1: TypedContractMethod<
    [commitment: BytesLike],
    [string],
    "view"
  >;

  verifyBlobDataIsAvailable: TypedContractMethod<
    [versionedHash: BytesLike],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calcBlobHashV1"
  ): TypedContractMethod<[commitment: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "verifyBlobDataIsAvailable"
  ): TypedContractMethod<[versionedHash: BytesLike], [void], "view">;

  filters: {};
}
