/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  BlobsLib,
  BlobsLibInterface,
} from "../../../src/libraries/BlobsLib";

const _abi = [
  {
    inputs: [],
    name: "BlobNotFoundInTx",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "BlobVerificationInvalidBLSModulus",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "BlobVerificationInvalidFieldElementCount",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "BlobVerificationInvalidInputLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "BlobVerificationInvalidOutputLength",
    type: "error",
  },
  {
    inputs: [],
    name: "BlobVerificationPointEvaluationFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "KZGInputBadCommitmentLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "KZGInputBadInputLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "got",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "KZGInputBadProofLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "commitment",
        type: "bytes",
      },
    ],
    name: "calcBlobHashV1",
    outputs: [
      {
        internalType: "bytes32",
        name: "vh",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "versionedHash",
        type: "bytes32",
      },
    ],
    name: "verifyBlobDataIsAvailable",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346019576101c5908161001e823930815050f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80639ce67dea146100df5763da23b04d1461002f575f80fd5b60203660031901126100c75760043567ffffffffffffffff81116100c757366023820112156100c75780600401359067ffffffffffffffff82116100cb57604051601f8301601f19908116603f0116810167ffffffffffffffff8111828210176100cb5760405282815236602484840101116100c7575f602084819560246100bf96018386013783010152610141565b604051908152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffd5b60203660031901126100c7576100f66004356100f8565b005b905f5b8049801561013257831461012d575f198114610119576001016100fb565b634e487b7160e01b5f52601160045260245ffd5b509050565b630110b90960e61b5f5260045ffd5b80519081156101895760205f9183829460405193849301835e8101838152039060025afa1561017e575f516001600160f81b0316600160f81b1790565b6040513d5f823e3d90fd5b50505f9056fea2646970667358221220780cc77987eca49f22d8292d9f42ce5b0016e442fa6cfd973e97ebb26c5da12e64736f6c634300081c0033";

type BlobsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BlobsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BlobsLib__factory extends ContractFactory {
  constructor(...args: BlobsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BlobsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BlobsLib__factory {
    return super.connect(runner) as BlobsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BlobsLibInterface {
    return new Interface(_abi) as BlobsLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BlobsLib {
    return new Contract(address, _abi, runner) as unknown as BlobsLib;
  }
}
