/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT3__factory>;
    getContractFactory(
      name: "PoseidonT4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT4__factory>;
    getContractFactory(
      name: "ICensusValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICensusValidator__factory>;
    getContractFactory(
      name: "IProcessRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProcessRegistry__factory>;
    getContractFactory(
      name: "IZKVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IZKVerifier__factory>;
    getContractFactory(
      name: "BlobsLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlobsLib__factory>;
    getContractFactory(
      name: "ProcessIdLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProcessIdLib__factory>;
    getContractFactory(
      name: "StateRootLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StateRootLib__factory>;
    getContractFactory(
      name: "ProcessRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProcessRegistry__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;
    getContractFactory(
      name: "ResultsVerifierGroth16",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ResultsVerifierGroth16__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;
    getContractFactory(
      name: "StateTransitionVerifierGroth16",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StateTransitionVerifierGroth16__factory>;

    getContractAt(
      name: "PoseidonT3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT3>;
    getContractAt(
      name: "PoseidonT4",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT4>;
    getContractAt(
      name: "ICensusValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICensusValidator>;
    getContractAt(
      name: "IProcessRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IProcessRegistry>;
    getContractAt(
      name: "IZKVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IZKVerifier>;
    getContractAt(
      name: "BlobsLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlobsLib>;
    getContractAt(
      name: "ProcessIdLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProcessIdLib>;
    getContractAt(
      name: "StateRootLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StateRootLib>;
    getContractAt(
      name: "ProcessRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProcessRegistry>;
    getContractAt(
      name: "Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;
    getContractAt(
      name: "ResultsVerifierGroth16",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ResultsVerifierGroth16>;
    getContractAt(
      name: "Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;
    getContractAt(
      name: "StateTransitionVerifierGroth16",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StateTransitionVerifierGroth16>;

    deployContract(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "PoseidonT4",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT4>;
    deployContract(
      name: "ICensusValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICensusValidator>;
    deployContract(
      name: "IProcessRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProcessRegistry>;
    deployContract(
      name: "IZKVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZKVerifier>;
    deployContract(
      name: "BlobsLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobsLib>;
    deployContract(
      name: "ProcessIdLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProcessIdLib>;
    deployContract(
      name: "StateRootLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StateRootLib>;
    deployContract(
      name: "ProcessRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProcessRegistry>;
    deployContract(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier>;
    deployContract(
      name: "ResultsVerifierGroth16",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ResultsVerifierGroth16>;
    deployContract(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier>;
    deployContract(
      name: "StateTransitionVerifierGroth16",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StateTransitionVerifierGroth16>;

    deployContract(
      name: "PoseidonT3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "PoseidonT4",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT4>;
    deployContract(
      name: "ICensusValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICensusValidator>;
    deployContract(
      name: "IProcessRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProcessRegistry>;
    deployContract(
      name: "IZKVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZKVerifier>;
    deployContract(
      name: "BlobsLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlobsLib>;
    deployContract(
      name: "ProcessIdLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProcessIdLib>;
    deployContract(
      name: "StateRootLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StateRootLib>;
    deployContract(
      name: "ProcessRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProcessRegistry>;
    deployContract(
      name: "Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier>;
    deployContract(
      name: "ResultsVerifierGroth16",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ResultsVerifierGroth16>;
    deployContract(
      name: "Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier>;
    deployContract(
      name: "StateTransitionVerifierGroth16",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StateTransitionVerifierGroth16>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
